In [28]:
import pandas as pd
import numpy as np

# IMU Changes
- IMU data was recorded at 200hz.
- Because of the high frequency of this data, adding deltas (between 1000 and 1100 microseconds) were not significant to cause Kimera-VIO to crash.
- Will now modify raw data and change it to 100 hz.

In [29]:
df = pd.read_csv('./mav0/imu0/data.csv')

In [30]:
df['#timestamp [ns]'] = df['#timestamp [ns]'].astype('float64')

In [31]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22800 entries, 0 to 22799
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   #timestamp [ns]      22800 non-null  float64
 1   w_RS_S_x [rad s^-1]  22800 non-null  float64
 2   w_RS_S_y [rad s^-1]  22800 non-null  float64
 3   w_RS_S_z [rad s^-1]  22800 non-null  float64
 4   a_RS_S_x [m s^-2]    22800 non-null  float64
 5   a_RS_S_y [m s^-2]    22800 non-null  float64
 6   a_RS_S_z [m s^-2]    22800 non-null  float64
dtypes: float64(7)
memory usage: 1.2 MB


In [32]:
# Reducing to 100 hz
df = df.iloc[::2]

In [33]:
df.shape

(11400, 7)

In [34]:
np.unique(np.diff(df['#timestamp [ns]']), return_counts=True)

(array([ 9999872., 10000128.]), array([5700, 5699]))

In [35]:
(21096448 - 18903552)/1000

2192.896

### Introducing Minor Variation in IMU Timestamps

In [9]:
random_nanoseconds_to_add = np.random.uniform(0, 1000000, 10)

In [761]:
#random_nanoseconds_to_add = np.append(random_nanoseconds_to_add, [0,0,0])

In [762]:
random_nanoseconds_to_add

array([308214.61441624, 685186.26805477, 726769.55699726, 770577.69431322,
       390035.21969727, 618651.25075812,  72658.03245128, 598611.17246488,
       370253.88026937, 593170.62374219])

In [763]:
default_ts = df['#timestamp [ns]'].values

In [764]:
default_ts

array([1.41339321e+18, 1.41339321e+18, 1.41339321e+18, ...,
       1.41339333e+18, 1.41339333e+18, 1.41339333e+18])

In [765]:
modified_ts = np.array([])

In [766]:
# i=0
# for def_ts in default_ts:
#     if i < 1000:
#         modified_ts = np.append(modified_ts, def_ts)
#     else:
#         modified_ts = np.append(modified_ts, float(def_ts - np.random.choice(random_nanoseconds_to_add, 1)[0]))
#     i += 1

In [767]:
for def_ts in default_ts:
    modified_ts = np.append(modified_ts, float(def_ts - np.random.choice(random_nanoseconds_to_add, 1)[0]))

In [768]:
modified_ts[1]- modified_ts[0]

10228480.0

In [769]:
df['#timestamp [ns]'] = modified_ts

In [770]:
np.unique(np.diff(df['#timestamp [ns]']), return_counts=True)

(array([ 9302016.,  9302272.,  9345792.,  9346048.,  9387264.,  9387520.,
         9453824.,  9454080.,  9474048.,  9474304.,  9479424.,  9479680.,
         9537536.,  9537792.,  9581312.,  9581568.,  9599488.,  9599744.,
         9619456.,  9619712.,  9622784.,  9623040.,  9643264.,  9643520.,
         9663232.,  9663488.,  9682432.,  9682688.,  9684736.,  9684992.,
         9689344.,  9689600.,  9702400.,  9702656.,  9704704.,  9704960.,
         9709568.,  9709824.,  9714944.,  9715200.,  9751296.,  9751552.,
         9764352.,  9764608.,  9771264.,  9771520.,  9771776.,  9776896.,
         9777152.,  9791488.,  9791744.,  9796864.,  9797120.,  9822464.,
         9822720.,  9827840.,  9828096.,  9848064.,  9848320.,  9866240.,
         9866496.,  9871616.,  9871872.,  9891840.,  9892096.,  9907712.,
         9907968.,  9913088.,  9913344.,  9914624.,  9914880.,  9917952.,
         9918208.,  9933312.,  9933568.,  9937920.,  9938176.,  9956096.,
         9956352.,  9958400.,  9958656

### End Section

In [36]:
df['#timestamp [ns]']

0        1.413393e+18
2        1.413393e+18
4        1.413393e+18
6        1.413393e+18
8        1.413393e+18
             ...     
22790    1.413393e+18
22792    1.413393e+18
22794    1.413393e+18
22796    1.413393e+18
22798    1.413393e+18
Name: #timestamp [ns], Length: 11400, dtype: float64

In [37]:
df['#timestamp [ns]'] = df['#timestamp [ns]'].apply(lambda x: f"{x:.0f}")

In [38]:
df['#timestamp [ns]']

0        1413393212225760512
2        1413393212235760384
4        1413393212245760512
6        1413393212255760384
8        1413393212265760512
                ...         
22790    1413393326175760384
22792    1413393326185760512
22794    1413393326195760384
22796    1413393326205760512
22798    1413393326215760384
Name: #timestamp [ns], Length: 11400, dtype: object

In [39]:
df.head(20)

#timestamp [ns]  w_RS_S_x [rad s^-1]  w_RS_S_y [rad s^-1]  \
0   1413393212225760512             0.094946             0.020246   
2   1413393212235760384            -0.011170             0.027925   
4   1413393212245760512            -0.092153             0.036303   
6   1413393212255760384            -0.005585             0.009076   
8   1413393212265760512             0.061436             0.023736   
10  1413393212275760384             0.009774             0.028623   
12  1413393212285760512            -0.032114             0.042586   
14  1413393212295760384            -0.030718             0.041888   
16  1413393212305760512            -0.000698             0.024435   
18  1413393212315760384             0.032812             0.008378   
20  1413393212325760512             0.006283             0.011170   
22  1413393212335760384            -0.028623             0.037001   
24  1413393212345760512            -0.018151             0.048171   
26  1413393212355760384             0.020944             0.016755   
28  1413393212365760512             0.009076             0.005585   
30  1413393212375760384            -0.016057             0.041888   
32  1413393212385760512            -0.012566             0.050964   
34  1413393212395760384             0.001396             0.000698   
36  1413393212405760512            -0.011170             0.028623   
38  1413393212415760384             0.001396             0.022340   

    w_RS_S_z [rad s^-1]  a_RS_S_x [m s^-2]  a_RS_S_y [m s^-2]  \
0              0.058643           9.128357           0.106239   
2              0.069813           9.398040           1.618097   
4              0.078889           8.989429          -0.130755   
6              0.113795           9.299973          -1.234003   
8              0.091455           9.275456           0.073550   
10             0.060039           9.471589           0.400438   
12             0.086568           9.332662           0.122583   
14             0.094946           9.659550          -0.375922   
16             0.077493           9.291801          -0.490333   
18             0.075398           9.447073          -0.098067   
20             0.097738           9.447073           0.441299   
22             0.091455           9.757617           0.000000   
24             0.070511           9.324490          -0.482160   
26             0.087965           9.201907          -0.179789   
28             0.083078           9.487934           0.138928   
30             0.067021           9.545139           0.032689   
32             0.075398           9.455245          -0.310544   
34             0.099833           9.250940           0.138928   
36             0.084474           9.626861          -0.253338   
38             0.076794           9.806650          -0.343233   

    a_RS_S_z [m s^-2]  
0           -2.606934  
2           -2.705001  
4           -2.713173  
6           -2.476179  
8           -2.582418  
10          -2.606934  
12          -2.705001  
14          -2.917478  
16          -2.598762  
18          -2.655968  
20          -2.737690  
22          -2.868445  
24          -2.500696  
26          -2.574246  
28          -2.786723  
30          -2.835756  
32          -2.680484  
34          -2.549729  
36          -2.958339  
38          -2.884790

In [40]:
df.shape

(11400, 7)

In [41]:
df.to_csv('./mav0/imu0/data_modified.csv', index=False)

In [42]:
!cp ./mav0/imu0/data_modified.csv /home/shiva/Datasets/V2_01_easy/V2_01_easy/mav0/imu0/data.csv